mode: "dev"

mysql:
  host: "localhost"
  port: 3306
  suffix: "charset=utf8mb4&parseTime=True&loc=Local" #后缀
  dbname: "wusidb"
  username: "root"
  password: "123456"
  max_open_conns: 200
  max_idle_conns: 50


log:
  level: "debug"
  filename: "./logs/gin-base-cli.log"
  max_size: 10
  max_age: 365
  max_backups: 5